package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
)

func main() {
	var fileName string

	if len(os.Args) == 2 {
		fileName = os.Args[1]
	} else {
		fileName = "input.txt"
	}

	initNums := readInput(fileName)

	fmt.Printf("The sum of the 2000th number generated by each buyer is %d\n", Part1(initNums))
}

func Part1(secretNums []int) int {
	total := 0

	for _, secretNum := range secretNums {
		for range 2000 {
			secretNum = evolve(secretNum)
		}
		total += secretNum
	}

	return total
}

func readInput(filePath string) []int {
	file, err := os.Open(filePath)
	if err != nil {
		fmt.Printf("Error opening %s", filePath)
		return nil
	}
	defer file.Close()

	initNums := []int{}

	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := scanner.Text()
		lineValue, _ := strconv.Atoi(line)

		initNums = append(initNums, lineValue)
	}

	return initNums
}

func evolve(secret int) int {
	// step 1
	secret = secret ^ (secret * 64)
	secret = secret % 16777216

	// step 2
	secret = secret ^ (secret / 32)
	secret = secret % 16777216

	// step 3
	secret = secret ^ (secret * 2048)
	secret = secret % 16777216

	return secret
}
